### ISSUE TITLE
It doesn't seem work with emmVRC

### ISSUE THREAD

**Issue by UrLittleDashie** [Astrum-Project/AstralRiskAcceptance#1]

**Comment by xKiraiChan** [comment]
I am unsure why this is the case, the hook looks completely valid but it doesn't work

**Comment by UrLittleDashie** [comment]
I don't understand anything abt coding but maybe emmVRC uses it's own hook that bypass the game hook ?

**Comment by EntityReborn** [comment]
Bump on this!

**Comment by xKiraiChan** [comment]
This should be fixed with 201050c `>=0.4.0`
I don't use emmVRC because it has nothing in it, so you'll have to test it.
It works with VRChatUtilityKit and that has the same code.
@UrLittleDashie @EntityReborn

**Comment by rangerdanger8805** [comment]
i downloaded this and it wont fix my problem with the blood in the corners of my walls. how do i fix the blood? the blood will not go away, neither will the soft groaning from the rotting body in the basement.

Edit: I have fixed the blood

**Comment by EntityReborn** [comment]
This worked. Thanks!
