### ISSUE TITLE
risky functions are not unlocked for ReMod CE

### ISSUE THREAD

**Issue by VRChat-is-NOT-awesome** [Astrum-Project/AstralRiskAcceptance#3]
ReMod CE is an open source mod that can be found in the Vrchat Modding Group. Unlike emmVRC, it doesn't use a blacklist so if risky functions were unlocked for it they would be unlocked for all worlds. It offers some functions that emm doesn't like: allowing you to type in a speed that's as high as you want, movement when flying that doesn't go up or down when you move forward and back based on where you're looking, and a customizable wireframe view of the world.

**Comment by xKiraiChan** [comment]
#5 adds support for ReMod CE
